// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKYO69M4aUC93pONXJgfjaAyG0Lqsop8g',
    appId: '1:864305747040:web:123e006ded43188a211f05',
    messagingSenderId: '864305747040',
    projectId: 'flashcard-quiz-app-f2542',
    authDomain: 'flashcard-quiz-app-f2542.firebaseapp.com',
    storageBucket: 'flashcard-quiz-app-f2542.appspot.com',
    measurementId: 'G-X5M6Y10P8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKXMIjraigulb_ypwNVVu8vRUbx-aquAc',
    appId: '1:864305747040:android:d2ed710abed862b7211f05',
    messagingSenderId: '864305747040',
    projectId: 'flashcard-quiz-app-f2542',
    storageBucket: 'flashcard-quiz-app-f2542.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCixOmyi_o6jYyuZm5h-yGCP_yDy8grBa8',
    appId: '1:864305747040:ios:c8d307224018279c211f05',
    messagingSenderId: '864305747040',
    projectId: 'flashcard-quiz-app-f2542',
    storageBucket: 'flashcard-quiz-app-f2542.appspot.com',
    iosBundleId: 'com.esmat.flashCardQuizApp',
  );
}
